### ISSUE TITLE
Redeclaration error

### ISSUE THREAD

**Issue by ndvo** [isacvale/vanilla_components#3]
If my vc_component have a script tag I get a `SyntaxError: redeclaration of let VCSearch`
If I remove the script tag (mine is doing nothing) I get a `TypeError: htmlDoc.getElementsByTagName(...)[0] is undefined`

I think it would be nicer if the script tag was optional on vc_components.
Actually, it would be really nice if all tags (script, style and the other) were optional and could be written in any order (I believe this is already the case).

**Comment by isacvale** [comment]
Humm... not really. As of today, each component requires a <script> and <style> tags, and a markup tag, that could be most anything (div, a, p, span, button, input, you name it). The style and script tags may come in any order, but the markup element must come first. Why? Because it can be anything. So in order to avoid writing code to pick this wildcard element, it just picks the first. It it is indeed a problem, we can do it differently (it just seemed the least complicated way, for now).

About the errors, a new version using classes will be uploaded soon. I ask you, please, to try and reproduce the error on that version. I couldn't reproduce it, so I can't fix it yet (are you declaring a new VCSearch instance? It is not necessary unless a compoenent is loaded dynamically).

**Comment by isacvale** [comment]
Ok, as of now, <style> and <script> are optional. VC will take as markup the first element (and its children) that are not style or script so you can write them in any order. But then again, it still only takes one markup element per component.
