### ISSUE TITLE
td element does not work on vc_components and only one variable per vc

### ISSUE THREAD

**Issue by ndvo** [isacvale/vanilla_components#5]
I did the following:

1- Created a simple vc_component:
```html
<tr class="article">
	<td class="name" ><a href="/$nome" title="visualizar $nome">$nome</a></td>
	<td class="modification">$modtime</td>
	<td class="size">$size</td>
	<td class="directory">False</td>
	<td><a href="/edit/$nome" title="editar $nome">Editar</a></td>
</tr>
```

Then on index.html, I did the following:

```html
<body>
<table id="list-of-articles"></table>
<script>
    var articleTable = document.getElementById("list-of-articles");
   articleTable.insertAdjacentHTML("beforeend",'<vc $nome="MyName" $modtime="MyTime" $size="MySize">linhatabela</vc>' );
    var vc_Table = new VCSearch(articleTable);
    vc_Table.loadComponent();
</script>
</body>
```

The result was unexpected:

```html
<a href="/MyName title="visualizar MyName">MyName</a>
```

If I simply change the tag used in vc_component to, say **div** or **table**, it works almost fine:
Only the first variable is substituted.

The problem seems to be related to a browser behavior... I am guessing that the **tr** element is only a part of a **table** element and thus is not loaded in the same way as other elements.

**Comment by isacvale** [comment]
The _one variable thing_ was an easy fix and it is already online.
The _<td> and <tr> one_ on the other hand, holy @#$%!
The solution might not be fully satisfactory but seems to me to be the most logical: VC really can't add <td> and <tr> for you. The reason is that if it did, it would break the format of your table, creating new columns and rows and it goes. You **can** create <td> and <tr> components in VC, but when loaded, they'll be stripped of their tag, so what you got to do is invoke them within the proper space. For example, you'd invoke:
```
    <table>
        <tr>
            <vc>TableRowComponent</vc>
        </tr>
        <tr>
            <td>
                 <vc>TableCellComponent</vc>
            </td>
        </tr>
    </table>
```
This does look like a fine print exception rule, but it seems to me to be the logical one.

**Comment by isacvale** [comment]
OK, the one variable is fixed, the table components is fixed* and the constructor function is fixed (and the style problem, which we hadn't detected). The system now relies more heavily on regular expressions, and as a result, it now allows multiple html tags in the root of the component (_but_ the constructor function will only target the first one - it is the component's coder who's in charge of then navigating through the DOM if he wants to target other elements in the component).
